"""Base emitter interface."""

from typing import Any, Dict, List


class BaseEmitter:
    """Base class for all Poetica emitters."""

    INDENT = "    "
    COMMENT = "#"
    LANG = "unknown"

    def emit(self, ir: Dict[str, Any]) -> str:
        lines = []
        header = self._header(ir)
        if header:
            lines.extend(header)

        name = ir.get("name", "program")
        lines.extend(self._fn_open(name))

        for op in ir.get("ops", []):
            code = self._emit_op(op)
            if code is not None:
                indent = self.INDENT * (op.get("indent", 0) + 1)
                for line in code if isinstance(code, list) else [code]:
                    lines.append(f"{indent}{line}")

        lines.extend(self._fn_close(name))

        footer = self._footer(ir)
        if footer:
            lines.extend(footer)

        return "\n".join(lines) + "\n"

    def _header(self, ir: Dict[str, Any]) -> List[str]:
        return [f"{self.COMMENT} Generated by Poetica (target: {self.LANG})"]

    def _footer(self, ir: Dict[str, Any]) -> List[str]:
        return []

    def _fn_open(self, name: str) -> List[str]:
        return []

    def _fn_close(self, name: str) -> List[str]:
        return []

    def _emit_op(self, op: Dict[str, Any]) -> str | List[str] | None:
        method = getattr(self, f'_op_{op["op"]}', None)
        if method:
            return method(op)
        return f"{self.COMMENT} {op['op']}: {op}"

    def _quote(self, value: str) -> str:
        """Smart-quote a value: keep as-is if it looks like an identifier."""
        if value.startswith('"') or value.startswith("'"):
            return value
        # Numbers
        try:
            float(value)
            return value
        except ValueError:
            pass
        # Booleans
        if value.lower() in ('true', 'false', 'none', 'null', 'nil'):
            return value
        # Identifiers (no spaces, starts with letter/underscore)
        if value.replace('.', '').replace('_', '').isalnum() and not value[0].isdigit():
            return value
        return f'"{value}"'
