"""Ode — Go emitter. Structured, concurrent, explicit."""

from typing import Any, Dict, List
from poetica.emitters.base import BaseEmitter


class GoEmitter(BaseEmitter):
    INDENT = "\t"
    COMMENT = "//"
    LANG = "go"

    def _header(self, ir) -> List[str]:
        return [f"// Generated by Poetica (target: go)", f'package main', f"", f'import "fmt"']

    def _fn_open(self, name: str) -> List[str]:
        safe = name.replace(':', '_').replace('-', '_').replace('.', '_')
        return [f"", f"func {safe}() {{"]

    def _fn_close(self, name: str) -> List[str]:
        return [f"}}"]

    def _footer(self, ir) -> List[str]:
        name = ir.get("name", "program").replace(':', '_').replace('-', '_').replace('.', '_')
        return [f"", f"func main() {{", f"\t{name}()", f"}}"]

    def _op_seed(self, op: Dict[str, Any]) -> str:
        return f"{op['name']} := {self._quote(op['value'])}"

    def _op_grow(self, op: Dict[str, Any]) -> str:
        return f"{op['name']} := build({self._quote(op['source'])})"

    def _op_emit(self, op: Dict[str, Any]) -> str:
        if op.get('label'):
            return f'fmt.Printf("[{op["label"]}] %v\\n", {self._quote(op["value"])})'
        return f"fmt.Println({self._quote(op['value'])})"

    def _op_pack(self, op: Dict[str, Any]) -> str:
        return f"{op['format']}Packed := compress({op['data']}, {self._quote(op['format'])})"

    def _op_lift(self, op: Dict[str, Any]) -> str:
        return f"deploy({op['name']}, {self._quote(op['dest'])})"

    def _op_use(self, op: Dict[str, Any]) -> str:
        params = ", ".join(f"{self._quote(str(v))}" for v in op.get('params', {}).values())
        if params:
            return f"result := {op['tool']}({params})"
        return f"result := {op['tool']}()"

    def _op_when(self, op: Dict[str, Any]) -> str:
        return f"if {op['condition']} {{"

    def _op_when_in(self, op: Dict[str, Any]) -> str:
        return f"if contains({op['container']}, {op['subject']}) {{"

    def _op_if(self, op: Dict[str, Any]) -> str:
        return f"if {op['left']} == {op['right']} {{"

    def _op_flow(self, op: Dict[str, Any]) -> str:
        return f"{op['dest']} := {op['source']}"

    def _op_bloom(self, op: Dict[str, Any]) -> str:
        return f"return {self._quote(op['value'])}"

    def _op_remember(self, op: Dict[str, Any]) -> str:
        return f'state[{self._quote(op["key"])}] = {self._quote(op["value"])}'

    def _op_learn(self, op: Dict[str, Any]) -> str:
        return f'model.Fit({self._quote(op["pattern"])})'

    def _op_for(self, op: Dict[str, Any]) -> str:
        lines = [f"for _, {op['var']} := range {op['collection']} {{"]
        if op.get('body'):
            lines.append(f"\t{op['body']}")
        lines.append("}")
        return lines
